# Generated by Django 4.2.5 on 2023-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('author', models.IntegerField()),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
